### ISSUE TITLE
No module named Queue

### ISSUE THREAD

**Issue by misterch0c** [ecstatic-nobel/analyst_arsenal#5]
Fyi I got this error
```
└┼─$─┤▶ ./opendir_certstream.py 
Traceback (most recent call last):
  File "./opendir_certstream.py", line 36, in <module>
    import Queue
ModuleNotFoundError: No module named 'Queue'
```

I fixed by changing `Queue` to `queue` on lines 36 & 319

**Comment by ecstatic-nobel** [comment]
@misterch0c try using Python 2.7.14. I currently working on getting the code Python 3 ready since Python 2 will not be maintain past 2020. If Python 2 returns no errors. I'll go ahead an close this issue.
