### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by misterch0c** [ecstatic-nobel/analyst_arsenal#6]
```
└┼─$─┤▶ ./opendir_urlscan.py automatic 5 exe
Summary:
    query_type     : automatic
    delta          : 5
    exclusions     : ['']
    file_dir       : ./InterestingFile/
    file_extension : exe
    kit_dir        : ./KitJackinSeason/
    quiet          : False
    timeout        : 30
    tor            : False
    verbose        : False

Getting IP Address...
Original IP: b'212.35.105.119'

[*] Original : http://micosoftoutlook.dns04.com/host/137.exe
[*] Session  : http://micosoftoutlook.dns04.com
Traceback (most recent call last):
  File "./opendir_urlscan.py", line 511, in <module>
    main()
  File "./opendir_urlscan.py", line 217, in main
    if "Index of " in resp.content:
TypeError: a bytes-like object is required, not 'str'
```
Any idea how I could fix this one? Not sure if I messed up somewhere with Python or something

**Comment by ecstatic-nobel** [comment]
@misterch0c try using Python 2.7.14. I'm currently working on getting the code Python 3 ready since Python 2 will not be maintained past 2020. If Python 2 returns no errors, I'll go ahead an close this issue.

**Comment by misterch0c** [comment]
I actually resorted to python3 because I couldn't get it work with python2:

```
┼─$─┤▶ python2 opendir_urlscan.py automatic 50 zip
Traceback (most recent call last):
  File "opendir_urlscan.py", line 50, in <module>
    import yaml
  File "/home/unknown/code/analyst_arsenal/_tp_modules/yaml/__init__.py", line 284
    class YAMLObject(metaclass = YAMLObjectMetaclass):
                               ^
SyntaxError: invalid syntax
```

**Comment by ecstatic-nobel** [comment]
What version of Python 2 are you running? Check with `python2 --version`. You should be running at least 2.7.14.

**Comment by misterch0c** [comment]
2.7.15

And this is the error I get using python2 to launch the other script
```
└┼─$─┤▶ python2 opendir_certstream.py 
Traceback (most recent call last):
  File "opendir_certstream.py", line 46, in <module>
    from Levenshtein import distance
  File "/home/unkn0wn/code/analyst_arsenal/_tp_modules/Levenshtein/__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
ImportError: cannot import name _levenshtein
```

**Comment by ecstatic-nobel** [comment]
Interesting, that's the same version I'm running. I noticed that if I install the packages with pip3 (being that you tried running the program with Python 3), I do see that **line 284** now looks similar:

**Line 284-286 of working _tp_modules/yaml/__init__.py**
```
            cls.yaml_dumper.add_representer(cls, cls.to_yaml)

class YAMLObject(object):
```

**Line 284 of _tp_modules/yaml/__init__.py after installing with pip3**
```
class YAMLObject(metaclass=YAMLObjectMetaclass):
```

Try running the contents of py_pkg_update.sh manually.
```
rm -rf _tp_modules/* && sudo pip install -r requirements.txt -t _tp_modules/
```

If that doesn't work, please provide the output of the pip install and the Linux distribution and version you are running.

**Comment by misterch0c** [comment]
That solved it.
My bad for using Python3 in the first please, just saw it was mentioned in the readme
