### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'very_verbose'

### ISSUE THREAD

**Issue by baileywj** [ecstatic-nobel/analyst_arsenal#7]
https://github.com/ecstatic-nobel/analyst_arsenal/blob/5fd06ce7bd4d2e2ce266238135e30a9a74d5b2e3/commons.py#L405

Looks like because aa_urlscan parser has no option for 'very_verbose', commons.py throws exception on failed_message().

**Comment by ecstatic-nobel** [comment]
Thanks for reporting this. v1.6.2 has been merged to the master branch to fix this issue. Let me know if it works for you.

**Comment by baileywj** [comment]
All good! Working fine now, thanks.
